sudo: false

dist: trusty

language: cpp

compiler:
    - gcc
    - clang
env:
    matrix:
        # default options
        - CMAKE_BUILD_TYPE=Release
        - CMAKE_BUILD_TYPE=Debug 
        # turn on all options 
        # (dont use openmp for now cause travis seems to have problems)
        # (dont use vtk for now cause travis hasnt whitelisted this)
        - Aboria_USE_EIGEN=on CMAKE_BUILD_TYPE=Release
        - Aboria_USE_EIGEN=on CMAKE_BUILD_TYPE=Debug
    global:
        - secure: Us0XAC9as4WOpXotIR0dHd8jHt+c2M5KXGOSQmE+gX/o30GMtBE7V/YkzHvbql+t0H+OkfIaBvHxYk30KHqCYiQJJpsbjjvmCLxm/+f+Vuw0J5D6yrYRJBS+6gdflU0lF/M19S1Mjl5u3uf5kLnWli8h8Hw2ZAnzmD+2vxRYO3UHfio1ACLGE3o6tBuyt9scFg0Vrg0f37o6jBdCiWzYyReBnc2bFvZBACR9iTIPdO0hwe27Td0GaPJzxm4yq0gDu6itMGzRMk1XpV79dfA3jZj2xhZqXSam4weAawDzk8J8nb1Tjv3pajuvJVn4HZ/QQIAvq7A4D5/m/mVuV37sAZIdZd4aGt8LYz1f9F0rpFBYckN5BMOttkrHAsw6W4caCexNw2KI+M7Fkubre0EBxb1arQYpOlA5OdGCDYprckffA6JPx6PRO/Dh2bLD2Wok+HtMtLg8Yv8h1oD1FqQvB6T7WDtVnq4sf1VXi2gz6zGAOCVInjCossy5FXGGKEX4QYdCiKVaqpEsmPxfOeQ3X/mlz1z796kYgoUiRSHajsL5ZGi9q+ba5eo0KK6H22GxOq7gU+AahL+rpyiwTX54C05lbR8VhyOx9yVm9AUTr0E3nuUgPmPQypuDlLVuVjTFc0iIScAVymve7M/0n3VSoOFCtXncNWePm9E+sCglm2k=

matrix:
    include:
        # Documentation
        - compiler: gcc
          env: Travis_UPDATE_DOC=on CMAKE_BUILD_TYPE=Release 
        # Coverage
        - compiler: gcc
          env: Aboria_COVERAGE=on CMAKE_BUILD_TYPE=Debug Aboria_USE_EIGEN=on  

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
        #- libopenmpi-dev
    - libboost1.55-dev
    - libboost1.55-tools-dev
    - gcc-5
    - g++-5
    - clang-3.8
      # cant find this package
      #- libomp-dev
    - doxygen
    - xsltproc
    - docbook-xml 
    - docbook-xsl
    - texlive-latex-base

before_install:
- if [ "$Aboria_COVERAGE" == "on" ]; then pip install --user cpp-coveralls; fi
- if [ "$Aboria_USE_EIGEN" == "on" ]; then wget http://bitbucket.org/eigen/eigen/get/3.3.1.tar.gz; tar -xvf 3.3.1.tar.gz;mv eigen*/Eigen .;mv eigen*/unsupported .; fi

before_script:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
- uname -a
- printenv
- clang++ --version 2>&1 | grep clang
- g++ --version 2>&1 | grep g++
- gcov --version | grep gcov
- grep "#define BOOST_VERSION " /usr/include/boost/version.hpp
- doxygen --version
- if [ "$Travis_UPDATE_DOC" == "on" ]; then cp doc/user-config.jam ~; fi
- git config --global user.email "martinjrobins@gmail.com"
- git config --global user.name "Martin Robinson"
- git remote rm origin
- git remote add origin https://martinjrobins:${GH_TOKEN}@github.com/martinjrobins/Aboria.git

script:
- cmake -DAboria_COVERAGE=$Aboria_COVERAGE -DAboria_USE_EIGEN=$Aboria_USE_EIGEN -DEIGEN3_INCLUDE_DIR=. -DAboria_USE_OPENMP=$Aboria_USE_OPENMP -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE .
- make
- ctest --output-on-failure

after_success:
- if [ "$Aboria_COVERAGE" == "on" ]; then coveralls -t iMaUSA3Acf6gvM53zh91NYaJizXQqanKz -e cxxtest -i src --gcov /usr/bin/gcov-4.8 --gcov-options '\-lp'; fi
- if [ "$Travis_UPDATE_DOC" == "on" ] && [ "$TRAVIS_BRANCH" == 'master' ]; then source update_doc.sh; fi

notifications:
  email:
    recipients:
    - martinjrobins@gmail.com
